import thinky from '../thinky';

const type = thinky.type;

const Order = thinky.createModel('Order', {
    // Optional => not specified in bodies but generated by RethinkDB
    id              : type.string().optional(),
    category        : type.string(),
    code            : type.string(),
    price           : type.number(),
    effectivePrice  : type.number(),
    lowerPrice      : type.number(),
    name            : type.string(),
    buyerName       : type.string(),
    buyerFirstName  : type.string(),
    status          : type.string(),
    removed         : type.boolean().default(false),
    createdAt       : type.date().default(new Date()),
    editedAt        : type.date().default(new Date())
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
})

Order.pre('save', function (next) {
    this.editedAt = new Date()
    next();
});

Order.ensureIndex('createdAt')
Order.ensureIndex('editedAt')

Order.associate = () => {}

export default Order;